CREATE TABLE profiles (
    profile_id INT AUTO_INCREMENT PRIMARY KEY,
    users_id INT NOT NULL,
    bio VARCHAR(255) NULL,
    website VARCHAR(255) NULL,
    twitter_handle VARCHAR(255) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (users_id) REFERENCES users(users_id) ON DELETE CASCADE
);