CREATE TABLE default (
    default_id INT AUTO_INCREMENT PRIMARY KEY,
    default_column_name VARCHAR(255) NOT NULL,
    default_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    default_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);